build-deploy-server:
  image: docker:latest
  stage: build
  only:
    refs:
      - branches
    changes:
      - Waitingway.Backend.Database/**
      - Waitingway.Protocol/**
      - Waitingway.Backend.Server/**
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -f "Waitingway.Backend.Server/Dockerfile" -t "$CI_REGISTRY_IMAGE/server${tag}" .
    - docker push "$CI_REGISTRY_IMAGE/server${tag}"
    # deploy
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo -n "$DEPLOY_SSH_KEY" | base64 -d | ssh-add - >/dev/null
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh "$DEPLOY_SSH_USER@$DEPLOY_SSH_HOST" "sudo /home/deploy/deploy-waitingway.sh server $CI_COMMIT_BRANCH"
build-deploy-discord:
  image: docker:latest
  stage: build
  only:
    refs:
      - branches
    changes:
      - Waitingway.Backend.Database/**
      - Waitingway.Backend.Discord/**
  variables:
    DOCKER_HOST: tcp://docker:2375 
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -f "Waitingway.Backend.Discord/Dockerfile" -t "$CI_REGISTRY_IMAGE/discord${tag}" .
    - docker push "$CI_REGISTRY_IMAGE/discord${tag}"
    # deploy
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo -n "$DEPLOY_SSH_KEY" | base64 -d | ssh-add - >/dev/null
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh "$DEPLOY_SSH_USER@$DEPLOY_SSH_HOST" "sudo /home/deploy/deploy-waitingway.sh discord $CI_COMMIT_BRANCH"
